version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - proxy

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    depends_on:
      - proxy

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"